name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      TRIVY_SARIF_PATH: .trivy.sarif
    steps:
      - uses: actions/checkout@v4

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: ${{ env.TRIVY_SARIF_PATH }}
          ignore-unfixed: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.TRIVY_SARIF_PATH }}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sarifReportPaths=${{ env.TRIVY_SARIF_PATH }}
