name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy.sarif
          ignore-unfixed: true
      - name: Sarif Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: |
            trivy.sarif
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sarifReportPaths=custom.sarif